Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,4 +1,4 @@
-name: CodeQL Analysis, Bandit Scan, Debricked Security Scan, and Codacy Security Scan
+name: CodeQL Analysis, Bandit Scan, Debricked Security Scan, and SonarQube Scan
 
 on:
   push:
@@ -11,7 +11,7 @@ on:
 
 permissions:
   contents: read
-  security-events: write # Required for uploading SARIF files
+  security-events: write  # Required for uploading SARIF files
 
 jobs:
   analyze_codeql:
@@ -75,7 +75,7 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout Repository
+      - name: Checkout code
         uses: actions/checkout@v4
 
       - name: Run Codacy Analysis CLI
@@ -83,15 +83,51 @@ jobs:
         with:
           project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
           verbose: true
-          output: .github/codacy/results.sarif
+          output: results.sarif
           format: sarif
           gh-code-scanning-compat: true
-          max-allowed-issues: 2147483647
+          max-allowed-issues: 2147483647  # Allow all issues, can be adjusted as needed
+
+      - name: Check if SARIF file exists
+        run: |
+          if [ -f "results.sarif" ]; then
+            echo "SARIF file found"
+          else
+            echo "SARIF file not found"
+            exit 1
+          fi
 
       - name: Upload Codacy SARIF results
         uses: github/codeql-action/upload-sarif@v3
         with:
-          sarif_file: .github/codacy/results.sarif
+          sarif_file: results.sarif
           token: ${{ secrets.GITHUB_TOKEN }}
-          category: codacy-security-scan
+          category: codacy-analysis-unique-category
           wait-for-processing: true
+
+  # sonarqube_scan:
+  #   name: SonarQube Analysis
+  #   runs-on: ubuntu-latest
+
+  #   steps:
+  #     - name: Checkout Repository
+  #       uses: actions/checkout@v4
+
+  #     - name: Setup Java 17
+  #       uses: actions/setup-java@v3
+  #       with:
+  #         java-version: '17'
+  #         distribution: 'temurin'
+
+  #     - name: Analyze with SonarQube
+  #       uses: SonarSource/sonarqube-scan-action@v1.1.0
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
+  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Token added to your repository's secrets
+  #         SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  # URL of your SonarQube instance
+  #       with:
+  #         args: >
+  #           -Dsonar.projectKey=your_project_key
+  #           -Dsonar.sources=.
+  #           -Dsonar.language=python
+  #           -Dsonar.exclusions=**/test/**,**/docs/**
